### ISSUE TITLE
Pulling list of Google Photos albums returns limited set

### ISSUE THREAD

**Issue by skipmeister123** [laurentalacoque/TouchSelfie-extended#55]
When selecting an album to use during setup, I am presented with a limited subset of my actual albums.  Unfortunately, my target album isn't in this list.

**Comment by skipmeister123** [comment]
Aha... read the code, and found https://github.com/laurentalacoque/TouchSelfie-extended/blob/master/scripts/setup.py#L278

**Comment by laurentalacoque** [comment]
You're supposed to filter the list by typing Duke characters in the search field 😉

**Comment by skipmeister123** [comment]
Yes, but it only filters the items pulled from the server. The amount of 
items being pulled was 15. Therefore, I could not find it when filtering.
--
Hans Kokx

**Comment by laurentalacoque** [comment]
Hu oh!
This definitely is a bug 😉

**Comment by laurentalacoque** [comment]
Hey @skipmeister123 !
I think that I do understand what's happening.

Actually, it seems that ALL albums are effectively pulled from your album list. 
See here:
https://github.com/laurentalacoque/TouchSelfie-extended/blob/fc4199da84a051b665494427efcca2e051add355/scripts/setup.py#L269

They are filtered inside a for loop that populates the list based on your filter.
BUT the 'limit to 15 items' condition is wrong here:
https://github.com/laurentalacoque/TouchSelfie-extended/blob/fc4199da84a051b665494427efcca2e051add355/scripts/setup.py#L295

because it's based on the original list index and not the current number of inserted elements.

This is addressed by https://github.com/laurentalacoque/TouchSelfie-extended/pull/57

@skipmeister123 could you please tell me if this fixes your issue?

**Comment by skipmeister123** [comment]
I'm glad you figured it out. I actually solved the problem for myself by 
changing the value to something higher.  Since I've changed a lot of the 
other code, I wasn't going to pull in these changes to test.  I will bless 
it, in spirit, though. 😅
--
Hans Kokx
